# Generated by Django 5.0.3 on 2024-04-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contactus',
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='contactus',
        ),
    ]
